export const GET_ASSETS = "GET_ASSETS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CART = "GET_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SUBTRACT_PRODUCT = "SUBTRACT_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const SET_LOADING = "SET_LOADING";
